export enum GetPagedOrdersMpSortBy {
  OrderId = 'OrderId',
  Email = 'Email',
  FirstName = 'FirstName',
  LastName = 'LastName',
  TotalPrice = 'TotalPrice',
  CreatedAt = 'CreatedAt',
  UpdatedAt = 'UpdatedAt',
  Status = 'Status',
  Street = 'Street',
  City = 'City',
  BuildingNumber = 'BuildingNumber',
  ApartmentNumber = 'ApartmentNumber',
  ZipCode = 'ZipCode',
  Country = 'Country',
  DeliveryMethod = 'DeliveryMethod',
  PaymentMethod = 'PaymentMethod',
  PhoneNumber = 'PhoneNumber',
}
